version: '2'
 
services:
 
  gamecache-dns-ext:
    image: steamcache/steamcache-dns:latest
    container_name: gamecache-dns-ext
    ports:
      - "53"
    environment:
#      - USE_GENERIC_CACHE=false
#      - LANCACHE_IP=genericcache
      - STEAMCACHE_IP=192.168.1.240
      - ORIGINCACHE_IP=192.168.1.241
      - BLIZZARDCACHE_IP=192.168.1.242
      - UPLAYCACHE_IP=192.168.1.243
      - RENEGADEXCACHE_IP=192.168.1.244
      - WSUSCACHE_IP=192.168.1.245
      - UPSTREAM_DNS=8.8.8.8
    networks:
      enp1s0f1_vlan:
        ipv4_address: 192.168.1.253
    restart: unless-stopped
 
  gamecache-dns-int:
    image: steamcache/steamcache-dns:latest
    container_name: gamecache-dns-int
    ports:
      - "53:53"
    environment:
#      - USE_GENERIC_CACHE=false
#      - LANCACHE_IP=genericcache
      - STEAMCACHE_IP=172.16.1.240
      - ORIGINCACHE_IP=172.16.1.241
      - BLIZZARDCACHE_IP=172.16.1.242
      - UPLAYCACHE_IP=172.16.1.243
      - RENEGADEXCACHE_IP=172.16.1.244
      - WSUSCACHE_IP=172.16.1.245
      - UPSTREAM_DNS=8.8.8.8
    networks:
      - internal_lan
    restart: unless-stopped

  sniproxy:
    image: steamcache/sniproxy:latest
    container_name: gamecache-sniproxy
    ports:
      - "443:443"
    networks:
      - enp1s0f1_vlan
    restart: unless-stopped
 
  steamcache:
    image: steamcache/generic:latest
    container_name: steamcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      enp1s0f1_vlan:
        ipv4_address: 192.168.1.240
      internal_lan:
        ipv4_address: 172.16.1.240
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/gamecache/steam:/data/cache
      - /mnt/store/docker-volumes/gamecache/steam:/data/logs

  origincache:
    image: steamcache/generic:latest
    container_name: origincache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      enp1s0f1_vlan:
        ipv4_address: 192.168.1.241
      internal_lan:
        ipv4_address: 172.16.1.241
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/gamecache/origin:/data/cache
      - /mnt/store/docker-volumes/gamecache/origin:/data/logs

  blizzardcache:
    image: steamcache/generic:latest
    container_name: blizzardcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      enp1s0f1_vlan:
        ipv4_address: 192.168.1.242
      internal_lan:
        ipv4_address: 172.16.1.242
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/gamecache/blizzard:/data/cache
      - /mnt/store/docker-volumes/gamecache/blizzard:/data/logs

  uplaycache:
    image: steamcache/generic:latest
    container_name: uplaycache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      enp1s0f1_vlan:
        ipv4_address: 192.168.1.243
      internal_lan:
        ipv4_address: 172.16.1.243
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/gamecache/uplay:/data/cache
      - /mnt/store/docker-volumes/gamecache/uplay:/data/logs

  renegadexcache:
    image: steamcache/generic:latest
    container_name: renegadexcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      enp1s0f1_vlan:
        ipv4_address: 192.168.1.244
      internal_lan:
        ipv4_address: 172.16.1.244
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/gamecache/renegadex:/data/cache
      - /mnt/store/docker-volumes/gamecache/renegadex:/data/logs

  windowscache:
    image: steamcache/generic:latest
    container_name: windowscache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      enp1s0f1_vlan:
        ipv4_address: 192.168.1.245
      internal_lan:
        ipv4_address: 172.16.1.245
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/gamecache/windows:/data/cache
      - /mnt/store/docker-volumes/gamecache/windows:/data/logs

networks:
#  enp1s0f1_vlan:
#    external:
#      name: enp1s0f1_vlan
  enp1s0f1_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0f1
    ipam:
      config:
        - subnet: 192.168.1.0/24
  internal_lan:
    ipam:
      config:
        - subnet: 172.16.0.0/16
