version: '2'

services:

  gamecache-dns:
    image: steamcache/steamcache-dns:latest
    container_name: gamecache-dns
    ports:
      - "53"
    environment:
      - USE_GENERIC_CACHE=false
      # - LANCACHE_IP=genericcache
      - STEAMCACHE_IP=192.168.1.240
      - ORIGINCACHE_IP=192.168.1.241
      - BLIZZARDCACHE_IP=192.168.1.242
      - UPLAYCACHE_IP=192.168.1.243
      # - FRONTIERCACHE_IP=frontiercache
      # - RIOTCACHE_IP=riotcache
      - WINDOWSCACHE_IP=192.168.1.246
      - DISABLE_STEAM=false
      - DISABLE_ORIGIN=false
      - DISABLE_BLIZZARD=false
      - DISABLE_UPLAY=false
      - DISABLE_FRONTIER=true
      - DISABLE_RIOT=true
      - DISABLE_WINDOWS=false
      - UPSTREAM_DNS=8.8.8.8
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.253
    restart: unless-stopped
    volumes:
      - /srv/quickload/docker-volumes/gamecache/dns:/data
      - /srv/quickload/docker-volumes/gamecache/dns:/tmp
      - /srv/quickload/docker-volumes/gamecache/dns:/var/logs

  sniproxy:
    image: steamcache/sniproxy:latest
    container_name: gamecache-sniproxy
    ports:
      - "443:443"
    networks:
      - gamecache_vlan
    restart: unless-stopped

  steamcache:
    image: steamcache/generic:latest
    container_name: steamcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.240
    restart: unless-stopped
    volumes:
      - /srv/store/docker-volumes/gamecache/steam:/data/cache
      - /srv/store/docker-volumes/gamecache/steam:/data/logs

  origincache:
    image: steamcache/generic:latest
    container_name: origincache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.241
    restart: unless-stopped
    volumes:
      - /srv/store/docker-volumes/gamecache/origin:/data/cache
      - /srv/store/docker-volumes/gamecache/origin:/data/logs

  blizzardcache:
    image: steamcache/generic:latest
    container_name: blizzardcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.242
    restart: unless-stopped
    volumes:
      - /srv/store/docker-volumes/gamecache/blizzard:/data/cache
      - /srv/store/docker-volumes/gamecache/blizzard:/data/logs

  uplaycache:
    image: steamcache/generic:latest
    container_name: uplaycache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.243
    restart: unless-stopped
    volumes:
      - /srv/store/docker-volumes/gamecache/uplay:/data/cache
      - /srv/store/docker-volumes/gamecache/uplay:/data/logs

  windowscache:
    image: steamcache/generic:latest
    container_name: windowscache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.246
    restart: unless-stopped
    volumes:
      - /srv/store/docker-volumes/gamecache/windows:/data/cache
      - /srv/store/docker-volumes/gamecache/windows:/data/logs

networks:
  gamecache_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0f1
    ipam:
      config:
        - subnet: 192.168.1.0/24
