version: '3.4'

services:

  gamecache-dns:
    image: steamcache/steamcache-dns:latest
    container_name: gamecache-dns
    ports:
      - "53"
    environment:
      - USE_GENERIC_CACHE=false
      # - LANCACHE_IP=genericcache
      - STEAMCACHE_IP=192.168.1.240
      # - ORIGINCACHE_IP=origincache
      # - BLIZZARDCACHE_IP=blizzardcache
      # - UPLAYCACHE_IP=uplaycache
      # - FRONTIERCACHE_IP=frontiercache
      # - RIOTCACHE_IP=riotcache
      # - WINDOWSCACHE_IP=windowscache
      - DISABLE_STEAM=false
      - DISABLE_ORIGIN=true
      - DISABLE_BLIZZARD=true
      - DISABLE_UPLAY=true
      - DISABLE_FRONTIER=true
      - DISABLE_RIOT=true
      - DISABLE_WINDOWS=true
      - UPSTREAM_DNS=8.8.8.8
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.253
    restart: unless-stopped
    volumes:
      - gamecache-dns-volume:/data
      - gamecache-dns-volume:/tmp
      - gamecache-dns-volume:/var/logs

  steamcache:
    image: steamcache/generic:latest
    container_name: steamcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.240
    restart: unless-stopped
    volumes:
      - steamcache-volume:/data/cache
      - steamcache-volume:/data/logs

networks:
  gamecache_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0f1
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  gamecache-dns-volume:
    driver_opts:
      type: none 
      device: /srv/docker/gamecache/dns
      o: bind
  steamcache-volume:
    driver_opts:
      type: none 
      device: /srv/docker/gamecache/steam
      o: bind
