version: '2'

services:

  sniproxy:
    image: steamcache/sniproxy:latest
    container_name: steamcache-sniproxy
    ports:
      - "443:443"
    restart: unless-stopped

  steamcache-dns:
    image: steamcache/steamcache-dns:latest
    container_name: steamcache-dns
    depends_on:
      - sniproxy
    ports:
      - "53:53"
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=192.168.1.100
      - UPSTREAM_DNS=1.1.1.1
    restart: unless-stopped

  steamcache-monolithic:
    image: steamcache/monolithic:latest
    container_name: steamcache-monolithic
    depends_on:
      - steamcache-dns
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - /mnt/store/docker-volumes/gamecache/monolithic:/data/cache
      - /mnt/store/docker-volumes/gamecache/monolithic:/data/logs
