version: '3.4'

services:

  gamecache-dns:
    image: steamcache/steamcache-dns:latest
    container_name: gamecache-dns
    ports:
      - "53"
    environment:
      - USE_GENERIC_CACHE=false
      # - LANCACHE_IP=genericcache
      - STEAMCACHE_IP=192.168.1.240
      - ORIGINCACHE_IP=192.168.1.241
      - BLIZZARDCACHE_IP=192.168.1.242
      - UPLAYCACHE_IP=192.168.1.243
      # - FRONTIERCACHE_IP=frontiercache
      # - RIOTCACHE_IP=riotcache
      - WINDOWSCACHE_IP=192.168.1.246
      - DISABLE_STEAM=false
      - DISABLE_ORIGIN=false
      - DISABLE_BLIZZARD=false
      - DISABLE_UPLAY=false
      - DISABLE_FRONTIER=true
      - DISABLE_RIOT=true
      - DISABLE_WINDOWS=false
      - UPSTREAM_DNS=8.8.8.8
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.253
    restart: unless-stopped
    volumes:
      - gamecache-dns-volume:/data
      - gamecache-dns-volume:/tmp
      - gamecache-dns-volume:/var/logs

  sniproxy:
    image: steamcache/sniproxy:latest
    container_name: gamecache-sniproxy
    ports:
      - "443:443"
    networks:
      - gamecache_vlan
    restart: unless-stopped

  steamcache:
    image: steamcache/generic:latest
    container_name: steamcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.240
    restart: unless-stopped
    volumes:
      - steamcache-volume:/data/cache
      - steamcache-volume:/data/logs

  origincache:
    image: steamcache/generic:latest
    container_name: origincache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.241
    restart: unless-stopped
    volumes:
      - origincache-volume:/data/cache
      - origincache-volume:/data/logs

  blizzardcache:
    image: steamcache/generic:latest
    container_name: blizzardcache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.242
    restart: unless-stopped
    volumes:
      - blizzardcache-volume:/data/cache
      - blizzardcache-volume:/data/logs

  uplaycache:
    image: steamcache/generic:latest
    container_name: uplaycache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.243
    restart: unless-stopped
    volumes:
      - uplaycache-volume:/data/cache
      - uplaycache-volume:/data/logs

  windowscache:
    image: steamcache/generic:latest
    container_name: windowscache
    ports:
      - "80"
    environment:
      - CACHE_MEM_SIZE=1024m
      - CACHE_DISK_SIZE=1024g
    networks:
      gamecache_vlan:
        ipv4_address: 192.168.1.246
    restart: unless-stopped
    volumes:
      - windowscache-volume:/data/cache
      - windowscache-volume:/data/logs

networks:
  gamecache_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0f1
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  gamecache-dns-volume:
    driver_opts:
      type: none 
      device: /srv/docker/gamecache/dns
      o: bind
  steamcache-volume:
    driver_opts:
      type: none 
      device: /srv/docker/gamecache/steam
      o: bind
  origincache-volume:
    driver_opts:
      type: none
      device: /srv/docker/gamecache/origin
      o: bind
  blizzardcache-volume:
    driver_opts:
      type: none
      device: /srv/docker/gamecache/blizzard
      o: bind
  uplaycache-volume:
    driver_opts:
      type: none
      device: /srv/docker/gamecache/uplay
      o: bind
  windowscache-volume:
    driver_opts:
      type: none
      device: /srv/docker/gamecache/windows
      o: bind
